server {
    listen 8188;

    location /ping {
        default_type text/plain;
        return 200 'OK';
    }

    location / {
        proxy_pass http://127.0.0.1:8189;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_read_timeout 300s;
        client_max_body_size 0;
    }
}
